Dev
Transport-company/courier pull request #1
Opened 2021-01-20 13:07 UTC by vibriss

init models

2021-01-20 18:20 UTC, ramilmm requested changes

2021-01-20 18:20 UTC, ramilmm commented on pom.xml
> +			<artifactId>h2</artifactId>
используется и h2 и postgres? или что-то лишнее?

2021-01-20 18:20 UTC, ramilmm commented on src/main/java/com/training/courier/model/Courier.java
> +    private String name;
Курьер всё-таки человек, давайте хотя бы добавим ему фамилию, имя и возраст

2021-01-20 18:20 UTC, ramilmm commented on src/main/java/com/training/courier/model/Salary.java
> +public class Salary {
Я б добавил какие-то показатели для расчёта зп(например, количество доставок, количество отработанных часов....) + указывать за какой период эта зп

2021-01-20 18:20 UTC, ramilmm commented on src/main/resources/db/migration/V1_0_0_1__init_script.sql
> +    apartment                 varchar(4),
region (32) - Республика Северная Осетия - Алания - сразу вызывает ошибку
street (32) - улица "Территория, изъятая из земель подсобного хозяйства Всесоюзного центрального совета профессиональных союзов для организации крестьянского хозяйства" - сразу вызывает ошибку
house (4) - 71к4Г-Дс5 - сразу вызывает ошибку
app (4) - думаю тут тоже стоит увеличить

2021-01-20 18:20 UTC, ramilmm commented on src/main/java/com/training/courier/model/Client.java
> +    private String name;
Что такое name у клиента? Название клиента? Клиент - человек, курьер должен обращаться к клиенту по ФИО.

2021-01-20 18:27 UTC, ValeriyEmelyanov commented on pom.xml
> +			<artifactId>h2</artifactId>
обсуждали, что для продуктива будет postgres, для тестирования h2

2021-01-20 18:44 UTC, ValeriyEmelyanov commented on src/main/java/com/training/courier/model/Cargo.java
> +    private Long id;
Должна быть аннотация @Id. Первичный ключ должен быть, просто он не будет автоматически генерироваться. Дла остальных сущностей тоже.

2021-01-20 18:47 UTC, ValeriyEmelyanov commented on src/main/java/com/training/courier/model/Delivery.java
> +    private Courier courier;
@ManyToOne, у курьера много доставок

2021-01-20 18:49 UTC, ValeriyEmelyanov commented on src/main/java/com/training/courier/model/Delivery.java
> +public class Delivery {
Может так и назвать CourierDeliveri, чтобы не путаться.

2021-01-20 18:50 UTC, ValeriyEmelyanov commented on src/main/java/com/training/courier/model/Delivery.java
> +    private Boolean enabledNotifications;
скорее нет

2021-01-20 18:56 UTC, ValeriyEmelyanov commented on src/main/resources/db/migration/V1_0_0_1__init_script.sql
> +    id                             bigserial          NOT NULL PRIMARY KEY,
насколько знаю достаточно `id bigserial PRIMARY KEY`, без `NOT NULL`, postgress не позволит NULL в первичном ключе. (и далее тоже)

2021-01-20 20:05 UTC, vibriss commented on src/main/java/com/training/courier/model/Courier.java
> +    private String name;
Ок

2021-01-20 20:21 UTC, vibriss commented on src/main/java/com/training/courier/model/Salary.java
> +public class Salary {
Сходу не придумали, как сделать расчёт зарплаты курьера, поэтому оставили на потом. Это предварительная модель, которая точно поменяется.

2021-01-20 20:26 UTC, vibriss commented on src/main/java/com/training/courier/model/Cargo.java
> +    private Long id;
Ок

2021-01-21 17:31 UTC, vibriss commented on src/main/resources/db/migration/V1_0_0_1__init_script.sql
> +    region                       varchar(255)   NOT NULL,
@ValeriyEmelyanov, я спрашивал, на каком размере полей остановиться

2021-01-21 18:55 UTC, ramilmm commented on src/main/resources/db/migration/V1_0_0_1__init_script.sql
> +    region                       varchar(255)   NOT NULL,
По-моему, допустимо будет сделать так:
region 128
city 128
street 255
house 16
appartment 16

2021-01-23 19:54 UTC, ValeriyEmelyanov commented on src/main/java/com/training/courier/Urls.java
> +    String ROOT = "/";
Тут есть мой косяк. ROOT не может быть в текущей реализации "/", тогда в полном маршруте получается два слеша. Сделай ROOT = "".

2021-01-23 19:59 UTC, vibriss commented on src/main/java/com/training/courier/Urls.java
> +    String ROOT = "/";
Да, я видел этот комментарий в Core, у себя уже переделал, в следующем коммите это будет.

2021-01-25 05:43 UTC, ramilmm approved these changes

2021-01-26 17:42 UTC, closed without merging