Models
Transport-company/courier pull request #2
Opened 2021-01-22 11:11 UTC by vibriss

Созданы модели со всеми свойствами
Создан скрипт создания базы данных

2021-01-22 18:24 UTC, ValeriyEmelyanov commented on src/main/resources/application.yml
> +      path: /doc/swagger-ui.html
courier./doc/swagger-ui.html

2021-01-22 18:30 UTC, ValeriyEmelyanov commented on src/main/java/com/training/courier/model/Salary.java
> +public class Salary {
Для зарплаты не хватает за какой период начислена (не один раз в жизни), количество доставок, повышающий коэффициент за вес (например, если средний вес доставки больше ... можно какую-то шкалу), примерно так же повышающий коэффициент за габариты.

2021-01-23 12:40 UTC, vibriss commented on src/main/java/com/training/courier/model/Salary.java
> +public class Salary {
Добавил. Может, для колонки с деньгами использовать тип money?
https://metanit.com/sql/postgresql/2.3.php - вот в этой же статье нашел, которую ты скидывал Александру.

2021-01-23 20:04 UTC, ValeriyEmelyanov commented on src/main/java/com/training/courier/model/Salary.java
> +public class Salary {
надо выяснить какой тип Java соответствует money, и может быть все переделаем на money

2021-01-23 20:23 UTC, ValeriyEmelyanov commented on src/main/java/com/training/courier/model/Status.java
> +public enum Status {
Переименовать в CourierDelivery

2021-01-23 21:37 UTC, vibriss commented on src/main/java/com/training/courier/model/Salary.java
> +public class Salary {
На первой странице результатов поиска в гугле ни разу не упоминается о типе "money" в postgres. Для денег используется numeric или decimal. Так что менять ничего не будем, вопрос исчерпан. =)

2021-01-24 15:42 UTC, ramilmm requested changes

2021-01-24 15:42 UTC, ramilmm commented on src/main/java/com/training/courier/model/Client.java
> +    private String name;
тут вроде добавляем firstName, lastName, middleName?

2021-01-24 15:42 UTC, ramilmm commented on src/main/java/com/training/courier/model/Courier.java
> +    private Integer age;
меняем на день рождения

2021-01-24 15:44 UTC, ramilmm approved these changes

2021-01-25 13:09 UTC, ramilmm requested changes

2021-01-25 13:09 UTC, ramilmm commented on src/main/java/com/training/courier/model/Client.java
> +    private LocalDate birthDate;
Я думаю просто birthdate, без camelCase

2021-01-25 13:09 UTC, ramilmm commented on src/main/java/com/training/courier/model/Courier.java
> +    private LocalDate birthDate;
и тут birthdate

2021-01-25 13:09 UTC, ramilmm commented on src/main/java/com/training/courier/model/Salary.java
> +     * Date
Date? описание поля совсем неявное. Непонятно для чего нужно поле

2021-01-25 13:18 UTC, vibriss commented on src/main/java/com/training/courier/model/Client.java
> +    private LocalDate birthDate;
Валерий в комментарии к коду в Core предложил такой вариант. Я переделал  так у себя, чтобы было единообразие.
Изначально у меня был такой вариант:
/**
* Date of birth
*/
@column(name = "birthday", nullable = false)
private LocalDate birthday;

birthday                 date                NOT NULL,

Когда определимся с формулировкой этого поля в Core, я сделаю так же.

2021-01-25 13:21 UTC, vibriss commented on src/main/java/com/training/courier/model/Salary.java
> +     * Date
Да, пожалуй. По сути, это дата осуществления курьерской доставки. Могу переименовать в deliveryDate. Подойдет такой вариант?

2021-01-25 13:21 UTC, ramilmm commented on src/main/java/com/training/courier/model/Client.java
> +    private LocalDate birthDate;
ну можно было и оставить birthday, коммент я написал к тому что не нужно использовать camelCase в этом слове

2021-01-25 13:29 UTC, vibriss commented on src/main/java/com/training/courier/model/Client.java
> +    private LocalDate birthDate;
Понял

2021-01-25 13:52 UTC, ValeriyEmelyanov commented on src/main/java/com/training/courier/model/Salary.java
> +     * Date
Как мы обсуждали, у нас зарплата начисляется за каждый рабочий день, соответственно это дата рабочего дня или дата начисления, второе больше отражает суть, можно назвать accrualDate, или какие более подходящие варианты в английском языке?

2021-01-25 13:56 UTC, ValeriyEmelyanov commented on src/main/java/com/training/courier/model/CourierDelivery.java
> +    private Client client;
ManyToOne

2021-01-25 13:58 UTC, ValeriyEmelyanov commented on src/main/java/com/training/courier/model/CourierDelivery.java
> +    private Address sendingAddress;
Думаю здесь правильнее указать связь ManyToOne

2021-01-25 13:59 UTC, ValeriyEmelyanov commented on src/main/java/com/training/courier/model/CourierDelivery.java
> +    private Address shippingAddress;
Аналогично, правильнее указать связь ManyToOne

2021-01-25 14:02 UTC, ValeriyEmelyanov commented on src/main/java/com/training/courier/model/CourierDeliveryStatus.java
> +    CLOSED
Я бы передвинул порядок элементов, CLOSED поставил после DELIVERED. Сначала перечисляем статусы нормального процесса в порядке их возникновения, потом перечисляем исключительные ситуации. Если Нам придется в бизнес-логике сравнивать статусы, это сильно поможет.

2021-01-25 14:04 UTC, ValeriyEmelyanov commented on src/main/resources/application.yml
> +    url: jdbc:postgresql://localhost:5432/transportcompany_courier
для имени базы предлагаю просто courier

2021-01-25 20:46 UTC, vibriss commented on src/main/resources/application.yml
> +    url: jdbc:postgresql://localhost:5432/transportcompany_courier
ок

2021-01-26 04:41 UTC, ramilmm approved these changes

2021-01-27 05:27 UTC, ValeriyEmelyanov approved these changes

2021-01-27 14:25 UTC, merged